# Site settings
title: Faalisco
description: ''
siteName: Faalisco
keywords:
author: E Faalisco
type: website
image: /assets/images/image.jpg
url: https://enlighten.gm
permalink: /:categories/:title/
# Kramdown and Rouge
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
# Global Configuration
source: src
# Sass Settings
sass:
  add_charset: true
  sass_dir: _sass
  style: :compressed
# Collections Settings
collections_dir: my_collections
collections:
  projects:
    output: true
